import uuid
from file_handler import load_plants, save_plants, log_task
from datetime import date

def get_plants_text():
    plants = load_plants()
    if not plants:
        return "⚠️ No plants registered yet."
    
    msg = f"🪴 *YOU HAVE {len(plants)} PLANT(S)*\n\n"
    for p in plants:
        msg += f"🌿 *ID: {p['id']}*\n"
        msg += f"Name: {p['name']}\n"
        msg += f"Species: {p['species']}\n"
        for task, info in p["care_tasks"].items():
            # FIX: Replace underscore with space so Telegram Markdown doesn't crash
            clean_task = task.replace('_', ' ').title()
            msg += f"  - {clean_task}: every {info['every_days']} days (last: {info['last_done']})\n"
        msg += "━━━━━━━━━━━━━━━━━━\n"
    return msg

def log_care_task_bot(plant_id, task):
    plants = load_plants()
    today = str(date.today())
    
    for p in plants:
        if p["id"] == plant_id:
            if task in p["care_tasks"]:
                p["care_tasks"][task]["last_done"] = today
                save_plants(plants)
                log_task(p["id"], p["name"], task, today)
                return f"✅ '{task}' logged for {p['name']} on {today}!"
            else:
                return "❌ Invalid task name! Use: watering, fertilizing, pruning, or pest_check."
    return "❌ Plant ID not found!"

def suggest_watering(plant_name):
    """Simple database to suggest watering days based on plant name."""
    name = plant_name.lower()
    if "cactus" in name or "succulent" in name or "aloe" in name:
        return 14, "Cactaceae/Succulent"
    elif "fern" in name:
        return 3, "Fern"
    elif "rose" in name:
        return 2, "Rosa"
    elif "snake" in name or "sansevieria" in name:
        return 21, "Sansevieria"
    elif "pothos" in name or "monstera" in name:
        return 10, "Araceae"
    else:
        return 7, "Unknown species" 

def add_plant_bot(name, species, water_freq):
    """Saves the new plant generated by the Telegram bot."""
    plants = load_plants()
    plant_id = str(uuid.uuid4())[:4] 
    today = str(date.today())
    
    plant = {
        "id": plant_id,
        "name": name,
        "species": species,
        "care_tasks": {
            "watering":    {"every_days": water_freq, "last_done": today},
            "fertilizing": {"every_days": 30,         "last_done": today},
            "pruning":     {"every_days": 14,         "last_done": today},
            "pest_check":  {"every_days": 7,          "last_done": today},
        }
    }
    plants.append(plant)
    save_plants(plants)
    return plant_id